### ISSUE TITLE
Feat: support copy file

### ISSUE THREAD

**Issue by KKould** [tonbo-io/fusio#99]
> If the snapshot is on the same filesystem as the original database, the SST files will be hard-linked, otherwise SST files will be copied

https://rocksdb.org/blog/2015/11/10/use-checkpoints-for-efficient-snapshots.html

CheckPoint will "copy" the WAL corresponding to MemTable and the related SSTable in Version. However, tonbo supports multiple FileSystems based on fusio. I think fusio can copy file to solve this problem.
- ref issue: https://github.com/tonbo-io/tonbo/issues/209
- ref api: [copy](https://doc.rust-lang.org/beta/std/fs/fn.copy.html) & [hard_link](https://doc.rust-lang.org/beta/std/fs/fn.hard_link.html)

**Comment by KKould** [comment]
the semantics of `hard_link` and `copy_file` are not consistent. For example, when the files of hard_link are modified, the contents will change together, but `copy_file` will not.

**Comment by ethe** [comment]
It is not a good name, maybe we can choose another one, but the semantic would be good to me.
